### ISSUE TITLE
"OldSource" Folder

### ISSUE THREAD

**Issue by ConnorVG** [BoomaNation/Booma.Library#1]
I feel like this really doesn't need to be here. The point of a VCS is that changes are tracked, you don't need to hold on to old stuff.

**Comment by HelloKitty** [comment]
@ConnorVG Hello Connor, this repo is not yet complete. I'm working on importing all the git repos from BoomaNation to conslidate nearly 100% csprojs related to the Booma project into a single solution. OldSources is a temporary folder containing the old solutions and projects until the merge is complete.

Since it is incomplete, and I started consolidating a day or two ago it's not yet done. I'll close this issue when the switch is complete.

The commit history is probably misleading, this repo has only existed for two days. It's just a merge of all the other repos.

**Comment by ConnorVG** [comment]
Awesome, my bad!

**Comment by HelloKitty** [comment]
The final project that needed to be merged was merged. While the solution is now stable it's not prepared to produce packages that can be used to run any particular part of the project such as the Instance server or client. So work will continue.

However, b568215d6761e40c062a2526384c95f04461ffc8 closes this issue.
